"""Utils package initialization."""

from .exceptions import (
    AIRateLimitError,
    AIServiceError,
    BaseApplicationError,
    CodeAnalysisError,
    DatabaseError,
    ErrorCode,
    ForbiddenError,
    GitHubAPIError,
    GitHubPRNotFoundError,
    NotFoundError,
    RateLimitError,
    TaskFailedError,
    TaskNotFoundError,
    UnauthorizedError,
    UnsupportedFileTypeError,
    ValidationError,
    handle_exception,
)
from .logger import (
    LoggerMixin,
    configure_logging,
    get_logger,
    log_ai_request,
    log_api_request,
    log_api_response,
    log_github_api_call,
    log_performance,
    log_task_failure,
    log_task_start,
    log_task_success,
)

__all__ = [
    # Exceptions
    "BaseApplicationError",
    "ValidationError",
    "NotFoundError",
    "UnauthorizedError",
    "ForbiddenError",
    "RateLimitError",
    "GitHubAPIError",
    "GitHubPRNotFoundError",
    "AIServiceError",
    "AIRateLimitError",
    "TaskNotFoundError",
    "TaskFailedError",
    "DatabaseError",
    "CodeAnalysisError",
    "UnsupportedFileTypeError",
    "ErrorCode",
    "handle_exception",
    # Logging
    "configure_logging",
    "get_logger",
    "log_performance",
    "log_api_request",
    "log_api_response",
    "log_task_start",
    "log_task_success",
    "log_task_failure",
    "log_github_api_call",
    "log_ai_request",
    "LoggerMixin",
]
